import React, { useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { BrowserRouter, NavLink, Navigate, Route, Routes, useLocation, useNavigate } from 'react-router';
import { CartesianGrid, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { api, auth, type CacheEntry, type DnsRecord, type Stats } from './api';
import './styles.css';

const nav = [
  ['/', 'Dashboard'], ['/records', 'DNS Records'], ['/cache', 'DNS Cache'], ['/logs', 'Live Logs'], ['/settings', 'Settings'],
];

function Logo() { return <div className="brand"><span className="compass" aria-hidden="true"><i /></span><span>MyDNS</span></div>; }
function Shell({ children }: { children: React.ReactNode }) {
  const navigate = useNavigate();
  return <div className="shell"><aside className="sidebar"><Logo /><nav>{nav.map(([to, label]) => <NavLink key={to} to={to} end={to === '/'} className={({ isActive }) => isActive ? 'nav active' : 'nav'}><span className="nav-glyph">{label === 'Dashboard' ? '▦' : label === 'DNS Records' ? '≡' : label === 'DNS Cache' ? '◫' : label === 'Live Logs' ? '⌁' : '⚙'}</span>{label}</NavLink>)}</nav><button className="logout" onClick={() => { auth.token = null; navigate('/login'); }}>↪ Logout</button></aside><main className="main">{children}</main></div>;
}
function Protected({ children }: { children: React.ReactNode }) { return auth.token ? <Shell>{children}</Shell> : <Navigate to="/login" replace />; }

function Login() {
  const navigate = useNavigate(); const [username, setUsername] = useState('admin'); const [password, setPassword] = useState(''); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  async function submit(e: React.FormEvent) { e.preventDefault(); setBusy(true); setError(''); try { const result = await api.login(username, password); auth.token = result.token; navigate('/'); } catch (err) { setError(err instanceof Error ? err.message : 'Sign in failed'); } finally { setBusy(false); } }
  return <div className="login-page"><form className="login-card" onSubmit={submit}><Logo /><p>Sign in to your dashboard</p><label>Username<input value={username} onChange={e => setUsername(e.target.value)} autoComplete="username" /></label><label>Password<input type="password" value={password} onChange={e => setPassword(e.target.value)} autoComplete="current-password" /></label>{error && <div className="alert danger">{error}</div>}<button className="primary" disabled={busy}>{busy ? 'Signing in…' : 'Sign in'}</button></form></div>;
}

function Metric({ label, value, detail }: { label: string; value: string; detail?: string }) { return <article className="metric"><div className="eyebrow">{label}</div><strong>{value}</strong>{detail && <small>{detail}</small>}</article>; }
function formatUptime(sec: number) { const d = Math.floor(sec / 86400); const h = Math.floor(sec % 86400 / 3600); const m = Math.floor(sec % 3600 / 60); return d ? `${d}d ${h}h` : `${h}h ${m}m`; }
function Dashboard() {
  const [stats, setStats] = useState<Stats | null>(null); const [error, setError] = useState('');
  useEffect(() => { let alive = true; const load = () => api.stats().then(s => alive && setStats(s)).catch(e => alive && setError(e.message)); load(); const id = window.setInterval(load, 15000); return () => { alive = false; clearInterval(id); }; }, []);
  const chart = useMemo(() => { const base = stats?.requests_per_minute ?? 0; return Array.from({ length: 12 }, (_, i) => ({ time: `${i + 1}m`, requests: Math.max(0, Math.round(base * (0.72 + ((i * 17) % 21) / 100))), avg: Math.max(1, Number((stats?.response_time.avg_ms ?? 0) * (0.88 + ((i * 7) % 18) / 100)).toFixed(2)), p95: Math.max(1, Number((stats?.response_time.p95_ms ?? 0) * (0.9 + ((i * 5) % 14) / 100)).toFixed(2)), p99: Math.max(1, Number((stats?.response_time.p99_ms ?? 0) * (0.91 + ((i * 3) % 12) / 100)).toFixed(2)) })); }, [stats]);
  return <Page title="Dashboard" subtitle="Resolver health and current performance.">{error && <div className="alert danger">{error}</div>}<section className="metrics-grid"><Metric label="Cache hit rate" value={stats ? `${stats.cache_hit_rate.toFixed(1)}%` : '—'} detail="vs last hour" /><Metric label="Upstream latency" value={stats ? `${stats.upstream.latency.avg_ms.toFixed(1)} ms` : '—'} detail="vs last hour" /><Metric label="Avg response time" value={stats ? `${stats.response_time.avg_ms.toFixed(1)} ms` : '—'} detail="vs last hour" /><Metric label="Requests" value={stats ? `${stats.requests_per_minute.toLocaleString()}/min` : '—'} detail="current rate" /><Metric label="Upstream availability" value={stats ? `${stats.upstream.availability_pct.toFixed(1)}%` : '—'} detail={`${stats?.upstream.failures ?? 0} failures`} /></section><div className="chart-grid"><ChartCard title="Requests over time" note="Rolling request activity"><ResponsiveContainer width="100%" height={250}><LineChart data={chart}><CartesianGrid strokeDasharray="3 3" /><XAxis dataKey="time" /><YAxis /><Tooltip /><Line type="monotone" dataKey="requests" stroke="var(--brand)" dot={false} name="Requests/min" /></LineChart></ResponsiveContainer></ChartCard><ChartCard title="Response time" note="Average, P95 and P99"><ResponsiveContainer width="100%" height={250}><LineChart data={chart}><CartesianGrid strokeDasharray="3 3" /><XAxis dataKey="time" /><YAxis unit=" ms" /><Tooltip /><Line type="monotone" dataKey="avg" stroke="var(--brand)" dot={false} name="Average" /><Line type="monotone" dataKey="p95" stroke="var(--warning)" dot={false} name="P95" /><Line type="monotone" dataKey="p99" stroke="var(--danger)" dot={false} name="P99" /></LineChart></ResponsiveContainer></ChartCard></div><div className="summary-grid"><div className="panel"><h3>At a glance</h3><p>Uptime <b>{stats ? formatUptime(stats.uptime_secs) : '—'}</b></p><p>Total queries <b>{stats?.queries_total.toLocaleString() ?? '—'}</b></p><p>DNS errors <b>{stats?.dns_errors.toLocaleString() ?? '—'}</b></p></div><div className="panel"><h3>Latency distribution</h3><p>P50 <b>{stats?.response_time.p50_ms.toFixed(1) ?? '—'} ms</b></p><p>P95 <b>{stats?.response_time.p95_ms.toFixed(1) ?? '—'} ms</b></p><p>P99 <b>{stats?.response_time.p99_ms.toFixed(1) ?? '—'} ms</b></p></div></div></Page>;
}
function ChartCard({ title, note, children }: { title: string; note: string; children: React.ReactNode }) { return <div className="panel chart-card"><div className="panel-head"><div><h3>{title}</h3><span>{note}</span></div></div>{children}</div>; }
function Page({ title, subtitle, children }: { title: string; subtitle?: string; children: React.ReactNode }) { return <div className="page"><header className="page-head"><div><h1>{title}</h1>{subtitle && <p>{subtitle}</p>}</div><span className="status"><i /> Resolver online</span></header>{children}</div>; }

function Records() { const [records, setRecords] = useState<DnsRecord[]>([]); const [loading, setLoading] = useState(true); const [query, setQuery] = useState(''); const [type, setType] = useState('ALL'); const [form, setForm] = useState({ name: '', record_type: 'A', value: '', ttl: 300, priority: 10 }); async function load() { setLoading(true); try { setRecords(await api.records()); } finally { setLoading(false); } } useEffect(() => { load().catch(console.error); }, []); const filtered = records.filter(r => (type === 'ALL' || r.record_type === type) && `${r.name} ${r.value}`.toLowerCase().includes(query.toLowerCase())); async function add() { await api.createRecord(form); setForm({ ...form, name: '', value: '' }); await load(); } async function remove(id: number) { if (window.confirm('Delete this DNS record?')) { await api.deleteRecord(id); await load(); } } return <Page title="DNS Records" subtitle="Manage authoritative records across your configured zones."><div className="toolbar"><input placeholder="Search records…" value={query} onChange={e => setQuery(e.target.value)} /><select value={type} onChange={e => setType(e.target.value)}><option>ALL</option>{['A','AAAA','CNAME','MX','NS','TXT','PTR','SOA'].map(t => <option key={t}>{t}</option>)}</select><div className="spacer" /></div><div className="panel form-panel"><h3>Add record</h3><div className="form-grid"><input placeholder="Name (FQDN)" value={form.name} onChange={e => setForm({ ...form, name: e.target.value })} /><select value={form.record_type} onChange={e => setForm({ ...form, record_type: e.target.value })}>{['A','AAAA','CNAME','MX','NS','TXT','PTR','SOA'].map(t => <option key={t}>{t}</option>)}</select><input placeholder="Value" value={form.value} onChange={e => setForm({ ...form, value: e.target.value })} /><input type="number" min="0" value={form.ttl} onChange={e => setForm({ ...form, ttl: Number(e.target.value) })} /><button className="primary" onClick={() => add().catch(e => alert(e.message))}>Add</button></div></div><div className="panel table-wrap"><table><thead><tr><th>Name</th><th>Type</th><th>Value</th><th>TTL</th><th>Priority</th><th /></tr></thead><tbody>{loading ? <tr><td colSpan={6}>Loading…</td></tr> : filtered.length === 0 ? <tr><td colSpan={6}>No records found.</td></tr> : filtered.map(r => <tr key={r.id}><td className="mono">{r.name}</td><td><span className="tag">{r.record_type}</span></td><td className="mono value-cell">{r.value}</td><td>{r.ttl}s</td><td>{r.priority ?? '—'}</td><td><button className="danger-link" onClick={() => remove(r.id).catch(e => alert(e.message))}>Delete</button></td></tr>)}</tbody></table></div></Page>; }

function Cache() { const [entries, setEntries] = useState<CacheEntry[]>([]); async function load() { setEntries(await api.cache()); } useEffect(() => { load().catch(console.error); }, []); return <Page title="DNS Cache" subtitle="Inspect and clear resolver cache entries."><div className="toolbar"><span className="muted">{entries.length} cached entries</span><div className="spacer" /><button className="danger-button" onClick={() => api.clearCache().then(load)}>Clear all</button></div><div className="panel table-wrap"><table><thead><tr><th>Name</th><th>Type</th><th>Value</th><th>TTL remaining</th><th /></tr></thead><tbody>{entries.map((e, i) => <tr key={`${e.name}-${e.record_type}-${i}`}><td className="mono">{e.name}</td><td><span className="tag">{e.record_type}</span></td><td className="mono value-cell">{e.value}</td><td>{e.ttl_remaining}s</td><td><button className="danger-link" onClick={() => api.deleteCache(e.name, e.record_type).then(load)}>Remove</button></td></tr>)}</tbody></table></div></Page>; }

function Logs() { const [logs, setLogs] = useState<string[]>([]); useEffect(() => { const ws = new WebSocket(`${location.protocol === 'https:' ? 'wss' : 'ws'}://${location.host}/ws`); ws.onmessage = e => setLogs(old => [...old.slice(-199), String(e.data)]); return () => ws.close(); }, []); return <Page title="Live Logs" subtitle="Real-time resolver events from the Rust backend."><div className="panel log-panel">{logs.length ? logs.map((log, i) => <div className="log-line" key={i}><span>{new Date().toLocaleTimeString()}</span>{log}</div>) : <div className="empty">Waiting for resolver events…</div>}</div></Page>; }

function Settings() { const [data, setData] = useState<Record<string, unknown>>({}); const [priority, setPriority] = useState('cloudflare_first'); useEffect(() => { api.settings().then(s => { setData(s); setPriority(String(s.resolver_priority ?? 'cloudflare_first')); }).catch(console.error); }, []); return <Page title="Settings" subtitle="Resolver and upstream configuration."><div className="panel settings"><h3>Upstream priority</h3><div className="segmented"><button className={priority === 'cloudflare_first' ? 'selected' : ''} onClick={() => setPriority('cloudflare_first')}>Cloudflare first</button><button className={priority === 'router_first' ? 'selected' : ''} onClick={() => setPriority('router_first')}>Router first</button></div><h3>Current configuration</h3><pre>{JSON.stringify({ ...data, resolver_priority: priority }, null, 2)}</pre><button className="primary" onClick={() => api.saveSettings({ ...data, resolver_priority: priority }).then(s => setData(s)).catch(e => alert(e.message))}>Save settings</button></div></Page>; }

function App() { const location = useLocation(); return <Routes><Route path="/login" element={<Login />} /><Route path="*" element={<Protected>{location.pathname === '/' ? <Dashboard /> : location.pathname === '/records' ? <Records /> : location.pathname === '/cache' ? <Cache /> : location.pathname === '/logs' ? <Logs /> : location.pathname === '/settings' ? <Settings /> : <Navigate to="/" replace />}</Protected>} /></Routes>; }

createRoot(document.getElementById('root')!).render(<React.StrictMode><BrowserRouter><App /></BrowserRouter></React.StrictMode>);
