name: CI Policy - Branch
on:
  workflow_call:
jobs:
  lint:
    name: Lint
    uses: ./.github/workflows/ci-lint-light.yml
  static:
    name: Static
    uses: ./.github/workflows/ci-static-light.yml
  unit:
    name: Tests - Unit
    needs: [lint, static]
    uses: ./.github/workflows/ci-tests-unit.yml
