name: CI Policy - Main
on:
  workflow_call:
jobs:
  lint:
    uses: ./.github/workflows/ci-lint-full.yml
  static:
    uses: ./.github/workflows/ci-static-full.yml
  build:
    needs: [lint, static]
    uses: ./.github/workflows/ci-build-release.yml
  test-unit:
    name: Tests (Unit)
    needs: build
    uses: ./.github/workflows/ci-tests-unit.yml
  test-component:
    name: Tests (Component)
    needs: test-unit
    uses: ./.github/workflows/ci-tests-component.yml
  test-integration:
    name: Tests (Integration)
    needs: test-component
    uses: ./.github/workflows/ci-tests-integration.yml
  test-contract:
    name: Tests (Contract)
    needs: test-integration
    uses: ./.github/workflows/ci-tests-contract.yml
  test-smoke:
    name: Tests (Smoke)
    needs: test-contract
    uses: ./.github/workflows/ci-tests-smoke.yml
  test-e2e:
    name: Tests (E2E)
    needs: test-smoke
    uses: ./.github/workflows/ci-tests-e2e.yml
  security:
    needs: test-integration
    uses: ./.github/workflows/ci-security-audit.yml
  codeql:
    needs: test-integration
    uses: ./.github/workflows/ci-security-codeql.yml
  coverage-upload:
    needs: test-unit
    uses: ./.github/workflows/ci-coverage-upload.yml
    secrets: inherit
