name: CI Policy - Pull Request
on:
  workflow_call:
jobs:
  lint:
    uses: ./.github/workflows/ci-lint-full.yml
  build:
    needs: lint
    uses: ./.github/workflows/ci-build-release.yml
  unit:
    needs: build
    uses: ./.github/workflows/ci-tests-unit.yml
  backend-component:
    needs: unit
    uses: ./.github/workflows/ci-tests-backend-component.yml
  frontend-component:
    needs: unit
    uses: ./.github/workflows/ci-tests-frontend-component.yml
  backend-integration:
    needs: backend-component
    uses: ./.github/workflows/ci-tests-integration.yml
  contract:
    needs: [backend-integration, frontend-component]
    uses: ./.github/workflows/ci-tests-contract.yml
  smoke:
    needs: contract
    uses: ./.github/workflows/ci-tests-smoke.yml
  build-check:
    needs: contract
    uses: ./.github/workflows/ci-build-check.yml
