name: CI Policy - Nightly
on:
  workflow_call:
jobs:
  lint:
    uses: ./.github/workflows/ci-lint-nightly.yml
  build:
    needs: lint
    uses: ./.github/workflows/ci-build-release.yml
  unit:
    needs: build
    uses: ./.github/workflows/ci-tests-unit.yml
  backend-component:
    needs: unit
    uses: ./.github/workflows/ci-tests-backend-component.yml
  frontend-component:
    needs: unit
    uses: ./.github/workflows/ci-tests-frontend-component.yml
  backend-integration:
    needs: backend-component
    uses: ./.github/workflows/ci-tests-integration.yml
  contract:
    needs: [backend-integration, frontend-component]
    uses: ./.github/workflows/ci-tests-contract.yml
  smoke:
    needs: backend-integration
    uses: ./.github/workflows/ci-tests-smoke.yml
  e2e:
    needs: smoke
    uses: ./.github/workflows/ci-tests-e2e.yml
  extended:
    needs: [unit, backend-integration, smoke, e2e]
    uses: ./.github/workflows/ci-tests-extended.yml
  security:
    needs: [unit, backend-integration]
    uses: ./.github/workflows/ci-security-audit.yml
  codeql:
    needs: [unit, backend-integration]
    uses: ./.github/workflows/ci-security-codeql.yml
