name: CI Policy - Dev
on:
  workflow_call:
jobs:
  lint:
    uses: ./.github/workflows/ci-lint-full.yml
  static:
    uses: ./.github/workflows/ci-static-full.yml
  build:
    needs: [lint, static]
    uses: ./.github/workflows/ci-build-release.yml
  unit:
    needs: build
    uses: ./.github/workflows/ci-tests-unit.yml
  backend-component:
    needs: unit
    uses: ./.github/workflows/ci-tests-backend-component.yml
  frontend-component:
    needs: unit
    uses: ./.github/workflows/ci-tests-frontend-component.yml
  backend-integration:
    needs: backend-component
    uses: ./.github/workflows/ci-tests-integration.yml
  contract:
    needs: [backend-integration, frontend-component]
    uses: ./.github/workflows/ci-tests-contract.yml
  smoke:
    needs: contract
    uses: ./.github/workflows/ci-tests-smoke.yml
  e2e:
    needs: smoke
    uses: ./.github/workflows/ci-tests-e2e.yml
  security:
    needs: backend-integration
    uses: ./.github/workflows/ci-security-audit.yml
  codeql:
    needs: backend-integration
    uses: ./.github/workflows/ci-security-codeql.yml
  coverage-upload:
    needs: unit
    uses: ./.github/workflows/ci-coverage-upload.yml
    secrets: inherit
