name: CI Policy - Dev
on:
  workflow_call:
jobs:
  lint:
    name: Lint
    uses: ./.github/workflows/ci-lint-full.yml
  static:
    name: Static
    uses: ./.github/workflows/ci-static-full.yml
  build:
    name: Build
    needs: [lint, static]
    uses: ./.github/workflows/ci-build-release.yml
  tests-unit:
    name: Tests (Unit)
    needs: build
    uses: ./.github/workflows/ci-tests-unit.yml
  tests-component:
    name: Tests (Component)
    needs: tests-unit
    uses: ./.github/workflows/ci-tests-component.yml
  tests-integration:
    name: Tests (Integration)
    needs: tests-component
    uses: ./.github/workflows/ci-tests-integration.yml
  tests-contract:
    name: Tests (Contract)
    needs: tests-integration
    uses: ./.github/workflows/ci-tests-contract.yml
  tests-smoke:
    name: Tests (Smoke)
    needs: tests-contract
    uses: ./.github/workflows/ci-tests-smoke.yml
  tests-e2e:
    name: Tests (E2E)
    needs: tests-smoke
    uses: ./.github/workflows/ci-tests-e2e.yml
  security:
    needs: tests-integration
    uses: ./.github/workflows/ci-security-audit.yml
  codeql:
    needs: tests-integration
    uses: ./.github/workflows/ci-security-codeql.yml
  coverage-upload:
    needs: tests-unit
    uses: ./.github/workflows/ci-coverage-upload.yml
    secrets: inherit
